### PR TITLE
More signal bug fixes

### PR DESCRIPTION
**Pull request by lgessler**
- No more disappearing changes on save (ordering issue)
- No more double rendering of edges
- Some JS errors fixed

### CODE REVIEW

**Comment by amir-zeldes** [comment]
This looks better: the rendering is fixed now. However I can't annotate signals:

  * On loading the document, window.rstWebSignalTypes is undefined, which produces the first error at structure.py:124
  * When the signal tray is opened, no signal types populate the dropdowns and create_signal_item throws an error (not sure if this is a side effect of the first error - it only fires after clicking the (s) button)

Screen grab:

image

Can you reproduce or do you need more details? Logging on to dev and opening GUM_news_worship.txt may also help if the problem does not occur locally (it may also be an incomplete DB schema update if that is the case)

**Comment by lgessler** [comment]
Issue 2 is caused by issue 1, so these should have the same root cause.

I'm not seeing this on a fresh pull of `amir-zeldes/rstWeb develop`. Do you still see this when you clone it fresh and switch to `develop`? Do you know what might be causing it on your local instance?

**Comment by amir-zeldes** [comment]
Thanks for noticing the DB - that's good, though not related to the bug. I've tested and it's fine for newly imported documents: the problem is that the signals are not initialized correctly for documents already in the system. Admittedly this will only happen in upgrade scenarios, but a better behavior is probably to initialize signal types to 'none' + 'none' if a document is already present in the system for which signals were not imported.

**Comment by amir-zeldes** [comment]
There are probably two possible fixes: either update_schema in rstweb_sql can implant values on schema update for legacy documents, or the structure script can ensure a default value is always present. The latter sounds easier to me, but do you have a preference?

Also please pull, I fixed some small bugs in structure.js. Thanks!

**Comment by lgessler** [comment]
If the former sounds reasonable to you, I think it's closer to what the behavior should be.

**Comment by amir-zeldes** [comment]
Ok, do you want to take a stab at it?

**Pull request merged**
