### PR TITLE
Add REST API

### PR DESCRIPTION
**Pull request by arne-cl**
Hi Amir,

I added a REST API to rstWeb. It allows you to list/add/retrieve/convert/delete documents
programmatically / from the command line. For security reasons, I only added it to the
local installation. These are the endpoints (also listed at http://localhost:8080/api):

```
http://localhost:8080/api/convert (POST)
http://localhost:8080/api/documents (GET, DELETE)
http://localhost:8080/api/documents/{project_name} (GET, DELETE)
http://localhost:8080/api/documents/{project_name}/{file_name} (GET, POST, PUT, DELETE)
http://localhost:8080/api/projects (GET, DELETE)
http://localhost:8080/api/projects/{project_name} (GET, POST, DELETE)
```

The API has lots of tests. If you accept this pull request, I can set up TravisCI to run all tests
on each push to the repo automatically (looks like [this](https://travis-ci.org/arne-cl/discoursegraphs)) to make sure there are no regressions.

Best,
Arne

### CODE REVIEW

**Comment by amir-zeldes** [comment]
Hi Arne, thanks for contributing this, this is just a quick note to say I had a look but haven't had a chance to test it yet. 

Does something speak against also adding it to the server version with the same authentication as the rest of the interface? I think this functionality would be more useful to server admins than local users.

**Comment by arne-cl** [comment]
Hi Amir,

it absolutely makes more sense to have an API for the server version, I just wasn't sure about
the rights management (e.g. should only the admin account be able to delete projects).

**Comment by amir-zeldes** [comment]
Hi again Arne,

About the rights management, I think it makes sense for all actions to be admin only, since normal users ordinarily can't see documents not assigned to them, so even giving them read access to all documents with the API exceeds their current rights.

About the PR itself: I've had a look and unfortunately the absolute paths are breaking changes when running in server mode with a subfolder under the root. So on corpling, rstWeb lives in /var/www/html/rstweb/, to which Apache directs requests for https://corpling.uis.georgetown.edu/rstweb/. At this point, relative paths work, but 'absolute' paths such as `<script src="/script/admin.js"></script>` in admin.py are really interpreted as living in /var/www/html/ (or more to the point, https://corpling.uis.georgetown.edu/). rstWeb has no way of knowing it's running inside a folder called rstweb/ relative to the Apache server web root.

Can you figure out a way of implementing this that will work with relative paths?

**Comment by amir-zeldes** [comment]
Hi Arne - thanks for updating the code! We're making some changes elsewhere in the code for new features so if you'd like to merge this sooner would be better than later. Have you figured out a way to make this work in server and local mode?

**Comment by arne-cl** [comment]
Hi Amir,
I haven't looked at the server vs. local mode issue and I'll first need to fix a problem in the API itself.
I will close the pull request, keep rebasing on your development branch and open a new pull request once I've solved both issues.

**Comment by amir-zeldes** [comment]
Ok, let me know if you have any questions about the latest code base

**Pull request closed without merging**
